SELECT 
    ii.ITEM_ID, 
    ii.ITEM_NAME, 
    ii.RARITY
FROM 
    ITEM_INFO ii
LEFT JOIN 
    ITEM_TREE it ON ii.ITEM_ID = it.ITEM_ID
WHERE 
    it.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY 
    ii.ITEM_ID DESC;
