-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (OS.SUM_SALES * P.PRICE) AS SALES
FROM PRODUCT P 
JOIN 
    (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM_SALES
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID
    ) OS ON P.PRODUCT_ID = OS.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;