SELECT 
    YEAR(OS.SALES_DATE) AS YEAR, 
    MONTH(OS.SALES_DATE) AS MONTH, 
    UI.GENDER, 
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM 
    ONLINE_SALE OS 
JOIN 
    (SELECT USER_ID, GENDER 
     FROM USER_INFO 
     WHERE GENDER IS NOT NULL) UI 
ON UI.USER_ID = OS.USER_ID
GROUP BY 
    YEAR(OS.SALES_DATE), 
    MONTH(OS.SALES_DATE), 
    UI.GENDER
ORDER BY 
    YEAR(OS.SALES_DATE), 
    MONTH(OS.SALES_DATE), 
    UI.GENDER;
