SELECT CAR_ID, 
       CASE 
         WHEN EXISTS (
            SELECT 1 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R2
            WHERE R2.CAR_ID = R1.CAR_ID
              AND DATE(R2.START_DATE) <= '2022-10-16'
              AND DATE(R2.END_DATE) >= '2022-10-16'
         ) THEN '대여중'
         ELSE '대여 가능'
       END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R1
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;
