-- 코드를 작성해주세요
SELECT HRD.DEPT_ID, HRD.DEPT_NAME_EN, ROUND(AVG(HRE.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT HRD JOIN HR_EMPLOYEES HRE ON HRD.DEPT_ID = HRE.DEPT_ID
GROUP BY HRD.DEPT_ID
order by avg_sal desc
