SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) FP_MAX ON FP.CATEGORY = FP_MAX.CATEGORY AND FP.PRICE = FP_MAX.MAX_PRICE
WHERE
    FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY
    FP.PRICE DESC
